before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    binary: "{{ .ProjectName }}"
    main: ./cmd/{{ .ProjectName }}/{{ .ProjectName }}.go

# will not auto-publish the release
release:
  draft: true

checksum:
  algorithm: sha256
